name: usrenv
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - flask=1.1.2
  - marshmallow=3.6.1
  - pip=20.1.1
  - python=3.7.7
  - gunicorn=20.0.4
  - peewee=3.13.3
  - gunicorn=20.0.4
  - pip:
    - Flask-Injector==0.12.3